IMDB:
  AUTH: cookies
  EMAIL:
  PASSWORD:
  COOKIEATMAIN:
  LISTS: []
  IGNOREDLISTS: []
  TRACE: false
  HEADLESS: true
  BROWSERPATH:
SYNC:
  MODE: dry-run
  HISTORY: false
  RATINGS: true
  WATCHLIST: true
  LISTS: true
  TIMEOUT: 15m
TRAKT:
  CLIENTID: your-trakt-client-id
  CLIENTSECRET: your-trakt-client-secret
  TOKENFILE: trakt-token.json
TMDB:
  ENABLED: false
  READACCESSTOKEN:
  SESSIONID:
